### ISSUE TITLE
[BUG] Stacktrace when interrupting (SIGINT) a from-kafka pipeline

### ISSUE THREAD

**Issue by pdmack** [NVIDIA/Morpheus#93]
**Describe the bug**
Ctrl-C of a from-kafka pipeline yields an abort and stacktrace .
```
====Pipeline Started====
Stopping pipeline. Please wait... Press Ctrl+C again to kill.C
From Kafka rate: 93085messages [03:45, 413.64messages/s]
Deserialization rate: 93085messages [03:45, 413.64messages/s]
Preprocessing rate: 93085messages [03:45, 413.65messages/s]
Inference rate: 93085inf [03:45, 413.65inf/s]
Serialization rate: 93085messages [03:45, 413.65messages/s]
To Kafka rate: 93085messages [03:45, 413.65messages/s]
====Stopping Pipeline====
%3|1651867570.038|ERROR|rdkafka#consumer-1| [thrd:GroupCoordinator]: 1/1 brokers are down
F20220506 20:06:10.052778  4511 executor_base.cpp:395] Check failed: search != m_segments.end() [segment id: 57864; rank: 1]: not found
*** Check failure stack trace: ***
    @     0x7fb4ed097c0d  google::LogMessage::Fail()
    @     0x7fb4ed09a7a6  google::LogMessage::SendToLog()
    @     0x7fb4ed097705  google::LogMessage::Flush()
    @     0x7fb4ed09ad6a  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb4e4d834bd  neo::ExecutorBase::segment()
    @     0x7fb4e4d84602  neo::ExecutorBase::remove_segment()
    @     0x7fb4e4d87fae  neo::ExecutorBase::do_update()
    @     0x7fb4e4d86f01  neo::ExecutorBase::update()
    @     0x7fb4e4d8f93d  neo::StandaloneExecutor::stop()
    @     0x7fb4caf2ea6c  neo::pyneo::Executor::stop()
    @     0x7fb4caea3daf  (unknown)
    @     0x7fb4caea88aa  (unknown)
    @     0x561d62c03e7e  PyCFunction_Call
    @     0x561d62bec631  _PyObject_MakeTpCall
    @     0x561d62c03bfd  method_vectorcall
    @     0x561d62be7ffc  _PyEval_EvalFrameDefault
    @     0x561d62bf42a6  _PyFunction_Vectorcall
    @     0x561d62be3d9d  _PyEval_EvalFrameDefault
    @     0x561d62be2b76  _PyEval_EvalCodeWithName
    @     0x561d62bf433c  _PyFunction_Vectorcall
    @     0x561d62d0cc6a  _PyObject_Vectorcall.lto_priv.10
    @     0x561d62ba2441  context_run
    @     0x561d62beb0c6  cfunction_vectorcall_FASTCALL_KEYWORDS
    @     0x561d62c040bf  PyVectorcall_Call
    @     0x561d62be8d2e  _PyEval_EvalFrameDefault
    @     0x561d62bf42a6  _PyFunction_Vectorcall
    @     0x561d62be3d9d  _PyEval_EvalFrameDefault
    @     0x561d62bf42a6  _PyFunction_Vectorcall
    @     0x561d62be3d9d  _PyEval_EvalFrameDefault
    @     0x561d62bf42a6  _PyFunction_Vectorcall
    @     0x561d62be3d9d  _PyEval_EvalFrameDefault
    @     0x561d62bf42a6  _PyFunction_Vectorcall
Aborted (core dumped)```

**Steps/Code to reproduce bug**
Ctrl-C in the shell of a from-kafka pipeline

**Expected behavior**
No stacktrace. Graceful exit from pipeline.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of Morpheus install: [Docker/k8s]

**Environment details**
https://gist.github.com/pdmack/2f1924031e20995e99985cfd735fbbc3

**Additional context**
Add any other context about the problem here.

**Comment by mdemoret-nv** [comment]
We likely just need the Kafka stage to respect the shutdown signal

**Comment by mdemoret-nv** [comment]
@cwharris  can you look at this one since you have some experience with the Kafka source

**Comment by cwharris** [comment]
@pdmack Do you know if this is the C++ or the Python kafka source exhibiting the issue?

**Comment by pdmack** [comment]
New behavior in 22.06:
```
Stopping pipeline. Please wait... Press Ctrl+C again to kill.
Preprocessing rate: 1242messages [11:24,  5====Stopping Pipeline====
Unhandled exception in async loop! Exception:
Exception in callback Pipeline._do_run.<locals>.term_signal() at /opt/conda/envs/morpheus/lib/python3.8/site-packages/morpheus/pipeline/pipeline.py:404
Traceback (most recent call last):
  File "/opt/conda/envs/morpheus/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/morpheus/pipeline/pipeline.py", line 411, in term_signal
    self.stop()
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/morpheus/pipeline/pipeline.py", line 206, in stop
    s.stop()
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/morpheus/pipeline/source_stage.py", line 103, in stop
    self._source_stream.stop()
AttributeError: 'morpheus._lib.stages.KafkaSourceStage' object has no attribute 'stop'
Killing
Preprocessing rate: 1242messages [11:36,  5====Pipeline Complete====
Inference rate: 1242inf [11:36,  3.06inf/s]
```
